# Numpy (Numerical Python)

In [1]:
import numpy as np

In [2]:
arr= np.array([1,2,3,4,5])
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [3]:
# 2D Array

arr1 = np.array([[2,3,8],[5,7,9],[11,0,5]])
print(arr1)
print(type(arr1))
print(arr1.ndim) #ndim to calculate the dimension

[[ 2  3  8]
 [ 5  7  9]
 [11  0  5]]
<class 'numpy.ndarray'>
2


In [4]:
# indexing 
print(arr[1])
print(arr1[1][1])

2
7


In [5]:
arr3 = np.array([[[1,2,3],[7,8,9]],[[11,0,5],[45,69,78]]])
print(arr3)

[[[ 1  2  3]
  [ 7  8  9]]

 [[11  0  5]
  [45 69 78]]]


In [6]:
#Slicing 
print(arr[1:3])
print(arr1[1,1:3])
print(arr3[0,1,1:3])

[2 3]
[7 9]
[8 9]


In [7]:
#checking the datatype
print(arr.dtype)
arr4=np.array(["abhishek","rahul","harsh"])
print(arr4.dtype)

int32
<U8


In [8]:
#creating arrays with a defined datatype
arr5= np.array([1,2,3,4],dtype="S")
print(arr5)
print(arr5.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [9]:
arr6= np.array([1,2,3,4],dtype="i4")
print(arr6)
print(arr6.dtype)

[1 2 3 4]
int32


In [10]:
#Array Shape

print(arr.shape)
print(arr1.shape)
print(arr3.shape)

(5,)
(3, 3)
(2, 2, 3)


In [11]:
#joining array
x= np.array([1,88,78])
y= np.array([52,67,20])
z= np.concatenate((x,y))
print(z)

[ 1 88 78 52 67 20]


In [12]:
x1= np.array([[1,88],[78,26]])
y1= np.array([[52,67],[1,0]])
z1= np.concatenate((x1,y1),axis=0)
print(z1)

x1= np.array([[1,88],[78,26]])
y1= np.array([[52,67],[1,0]])
z1= np.concatenate((x1,y1),axis=1)
print(z1)

[[ 1 88]
 [78 26]
 [52 67]
 [ 1  0]]
[[ 1 88 52 67]
 [78 26  1  0]]


In [13]:
arr= np.array([1,2,3,4,5,7])
newarr= np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 7])]


In [14]:
# Ravel and flatten : multi to 1D
n= arr3.flatten()
print(n)
m= arr3.ravel()
print(m)

[ 1  2  3  7  8  9 11  0  5 45 69 78]
[ 1  2  3  7  8  9 11  0  5 45 69 78]


In [15]:
#Unique Function
k=np.array([1,2,9,7,5,8,1,2,8])
x=np.unique(k,return_index=True,return_counts=True)
print(x)

(array([1, 2, 5, 7, 8, 9]), array([0, 1, 4, 3, 5, 2], dtype=int64), array([2, 2, 1, 1, 2, 1], dtype=int64))


In [16]:
#Delete
k=np.array([1,2,9,7,5,8,1,2,8])
d=np.delete(k,[2])
print(d)

[1 2 7 5 8 1 2 8]
